name: development_build
on:
  # push:
  #   branches:
  #     - master

  workflow_dispatch:
concurrency:
  group: "${{ github.run_id }}"
  cancel-in-progress: true
jobs:
  development_build:
    runs-on: macos-26
    env:
      CERTIFICATE_PASSWORD: ${{ secrets.DEVELOPER_CERTIFICATE_PASSWORD }}
      KEYCHAIN_NAME: ${{ secrets.KEYCHAIN_NAME }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APP_STORE_CONNECT_KEY_ID: ${{ secrets.APP_STORE_CONNECT_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_KEY: ${{ secrets.APP_STORE_CONNECT_KEY }}

    steps:
    - name: Setup Git credentials
      run: |
        git config --global url."https://${{ secrets.ORG_GITHUB_USERNAME }}:${{ secrets.ORG_GITHUB_TOKEN }}@github.com/".insteadOf "git@github.com:"

    - uses: actions/checkout@v4

    - name: Select Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Download iOS Platform
      run: xcodebuild -downloadPlatform iOS
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'
        bundler-cache: true

    - name: Decode Developer Certificates
      run: echo "${{ secrets.DEVELOPER_IOS_CERTIFICATE }}" | base64 --decode > ./fastlane/Certificate.p12

    - name: Set up development certificates and profiles
      run: bundle exec fastlane get_development_profiles > /dev/null 2>&1
    
    - name: Create artifacts dir
      run: mkdir artifacts
      
    - name: Archive development build
      run: bundle exec fastlane development_build
  
    - name: Archive staging development build 
      run: bundle exec fastlane staging_build

    - name: Upload development ipa file
      uses: actions/upload-artifact@v4
      with:
        path: artifacts/
      